/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 */
/// <reference types="@cloudflare/workers-types" />

// @ts-expect-error — vinext patches next/cache with setCacheHandler at runtime
import { setCacheHandler } from "next/cache"
import { KVCacheHandler } from "vinext/cloudflare"
import handler from "vinext/server/app-router-entry"
import {
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  handleImageOptimization,
} from "vinext/server/image-optimization"

interface Env {
  ASSETS: Fetcher
  CACHE: KVNamespace
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>
      }
    }
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    setCacheHandler(new KVCacheHandler(env.CACHE))

    const url = new URL(request.url)

    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES]
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality })
            return result.response()
          },
        },
        allowedWidths
      )
    }

    return handler.fetch(request, env, ctx)
  },
}
